### ISSUE TITLE
Getting started on Mac OS X

### ISSUE THREAD

**Issue by DavidPhillipOster** [ewmailing/IupCocoa#1]
I forked your branch, and in Terminal did:

cd IupCocoa
make

---

The compile failed with many #include <gtk/...> file not found errors. So I coulduse some help getting started:

How do I configure for an OS X build? for an iOS build?
What do you need?

**Comment by ewmailing** [comment]
I have only focused on Mac for now. So I have nothing done for iOS. My starting point was a prior Cocoa attempt by somebody else. He admits he didn't really know Cocoa, but it looked like there was a lot of infrastructure that was usable. 

1) Switch to the branch called Cocoa

2) There is an Xcode project at Xcode/iup/iup.xcodeproj
(There is also a workspace at Xcode/iup.xcworkspace, but I think I was uncertain if I needed it.)

3) The new Cocoa specific source code is in src/cocoa
The Xcode project also mirrors this layout so you can expand the file trees in the left-panel. Pretty much all the code we need to write/change is in there. Generally, we shouldn't need to touch anything in the IUP core.

4) There are 2 targets in the Xcode project, the iup.framework and TestApp.
TestApp is a quick and dirty test app that I just modify as I want to test whatever I want to see. At some point, bringing in the real IUP test programs might be useful, but since so much is still unimplemented, a lot of that code still won't work and usually prevents anything from working (i.e. crashes). So feel free to modify TestApp's main.c as you need.

You should be able to make TestApp your target and hit Build/Run and a window with some widgets (whatever I was playing with last) will appear.

Notes:
- I recommend looking at my commit logs in the Cocoa branch. It may reveal some information about where I'm blocked or what I was trying to do. Most of the work so far has been filling in the easiest core areas and widgets (main event loop, window, button, label, image, etc.) A lot of that has just enough enough now that I can create the right widgets and get _something_ kind of appropriate on screen. The next big area which I was starting on, but did not finish and probably need help with is the positioning/size/layout. Right now none of the widgets get drawn to the correct place on the screen, nor with the correct size. I think I still have hardcoded initial sizes for a lot of widgets.
- IUP also has its own (common-code) mechanism for relative layouts. I think for that to work, I need to be able to return the correct sizing information to IUP.
- If I recall, fonts in particular are extremely important to IUP's layout system. And I was having the most problems there. (I usually don't do that much with Cocoa fonts.)
- I recommend having a Linux (or Windows) system to compare things to. I put Ubuntu in a VM as an example.
- It is theoretically possible to build IUP under GTK/Mac. I've never tried it, nor do I really want to.
- ARC is disabled (based on a conversation with you). We will be doing classic memory management with this backend since there is a lot of C interaction with the core.
- I haven't done anything with the Makefiles. I consider them low priority since Makefiles tend not to understand much about Mac/iOS specifics (e.g. app bundles, resources, SDKs, etc). I might never fix the Makefiles. Windows is also a pain for me, and actually Linux was to some degree too since the Pi initially violated assumptions, so I've been kicking around the idea of CMake. I found some CMake things from other people already made, but they would need to be modified for Apple-isms. Low priority for me.
- iOS would be great, but I think focusing on the Mac is the best course. IUP hasn't thought about mobile design. Getting Mac up first allows us to better understand IUP's design. With that understanding, I think we can do a better job figuring out iOS since that may ultimately require design changes in IUP.
- IUP has a couple of accessory libraries for additional widgets/functionality. (CD (for CanvasDraw I think) and IM (Image)). I am not focusing on these right now for simplicity. 
- I have been laxed with code formatting. At the moment I start caring, I'm thinking to just run clang-format on whole thing. Right now, I don't care.

**Comment by ewmailing** [comment]
I had a long thread on the IUP mailing list asking questions as I tried to get this branch working. It may reveal a lot of good information too.
It starts here:
https://www.mail-archive.com/iup-users@lists.sourceforge.net/msg01249.html
